name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Replace API Key
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Finde die Zeile mit dem API-Schl체ssel-Platzhalter
          API_KEY_LINE="const API_KEY = \"\$API_KEY\";"

          # Schreibe den korrekten Code mit dem Secret
          NEW_API_KEY_LINE="const API_KEY = \"${{ secrets.GEMINI_API_KEY }}\";"

          # Erstelle eine tempor채re Datei und ersetze den Platzhalter
          cp index.html index.tmp.html
          sed -i "s|${API_KEY_LINE}|${NEW_API_KEY_LINE}|g" index.tmp.html

          # Kopiere die tempor채re Datei zur체ck
          mv index.tmp.html index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
