name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Replace API Key
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Ersetze den Platzhalter direkt in der Datei und überschreibe sie
          sed -i 's/\$API_KEY/${GEMINI_API_KEY}/g' index.html
          
          # Zur Fehlersuche: Gib den Inhalt der modifizierten Datei aus
          echo "--- Inhalts-Check: index.html nach dem Ersetzen ---"
          cat index.html
          echo "----------------------------------------------------"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
