name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Replace API Key
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Lese den Inhalt von index.html
          html_content=$(cat index.html)

          # Ersetze den Platzhalter mit dem Secret
          updated_html_content=${html_content//\$API_KEY/${{ secrets.GEMINI_API_KEY }}}

          # Schreibe den aktualisierten Inhalt zurück in die Datei
          echo "$updated_html_content" > index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
